/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.28.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./WbtcController.client";
export declare namespace contracts {
    const WbtcController: {
        WbtcControllerQueryClient: typeof _1.WbtcControllerQueryClient;
        WbtcControllerClient: typeof _1.WbtcControllerClient;
    };
}
//# sourceMappingURL=index.d.ts.map